global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "tip-federation"
    honor_labels: true
    scheme: http
    authorization:
      type: Bearer
      credentials: "certtest-wpg05lctd6"
    static_configs:
      - targets:
          - "10.0.0.4:4000"
          - "10.0.0.5:4000"
          - "10.0.0.6:4000"

  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
