"""
python/shared/zk.py
TIP Protocol — Groth16 ZK proof verifier (Python, BN128)

Verifies the dedup proof generated by the VP SDK (shared/zk.js → generateDedupProof).
Uses py_ecc for BN128 elliptic curve pairings — no external binaries required.

SERVER (node):
  verify_dedup_proof(dedup_hash, proof)  →  True / False

Environment:
  ZK_SKIP_VERIFY=true   Skip verification — for tests only

Prerequisites:
  pip install py_ecc
  circuits/vkey.json must exist (generated by: node scripts/zk-setup.js)

© 2026 The AI Lab Intelligence Unobscured, Inc.
"""

import os
import json
import pathlib

from py_ecc.bn128 import (
    G1, G2,
    add, multiply, neg,
    pairing,
    FQ, FQ2, FQ12,
    is_on_curve,
    curve_order,
)

# ─── Load verification key ────────────────────────────────────────────────────

_VKEY_PATH = pathlib.Path(__file__).parent.parent.parent / "circuits" / "vkey.json"
_vkey_cache = None


def _load_vkey() -> dict:
    global _vkey_cache
    if _vkey_cache:
        return _vkey_cache
    if not _VKEY_PATH.exists():
        raise FileNotFoundError(
            f"ZK verification key not found at {_VKEY_PATH}. "
            "Run: node scripts/zk-setup.js"
        )
    with open(_VKEY_PATH) as f:
        _vkey_cache = json.load(f)
    return _vkey_cache


# ─── Point parsing ────────────────────────────────────────────────────────────
# snarkjs encodes all points as decimal strings.
# G1: ["x", "y", "1"]
# G2: [["x_c0", "x_c1"], ["y_c0", "y_c1"], ["1", "0"]]


def _parse_g1(point: list) -> tuple:
    """Parse a G1 affine point from snarkjs decimal string format."""
    return (FQ(int(point[0])), FQ(int(point[1])))


def _parse_g2(point: list) -> tuple:
    """Parse a G2 affine point from snarkjs decimal string format."""
    # snarkjs stores FQ2 as [c0, c1] where element = c0 + c1*u
    # py_ecc FQ2 constructor takes [c0, c1]
    x = FQ2([int(point[0][0]), int(point[0][1])])
    y = FQ2([int(point[1][0]), int(point[1][1])])
    return (x, y)


# ─── Groth16 verifier ─────────────────────────────────────────────────────────


def _groth16_verify(vkey: dict, public_signals: list, proof: dict) -> bool:
    """
    Groth16 verification equation (BN128):

      e(A, B) == e(vk_alpha, vk_beta) * e(vk_x, vk_gamma) * e(C, vk_delta)

    where:
      A     = pi_a  (G1)
      B     = pi_b  (G2)
      C     = pi_c  (G1)
      vk_x  = IC[0] + sum(signal[i] * IC[i+1])   (accumulated public inputs)
    """
    # Parse proof points
    pi_a = _parse_g1(proof["pi_a"])
    pi_b = _parse_g2(proof["pi_b"])
    pi_c = _parse_g1(proof["pi_c"])

    # Parse vkey points
    vk_alpha = _parse_g1(vkey["vk_alpha_1"])
    vk_beta  = _parse_g2(vkey["vk_beta_2"])
    vk_gamma = _parse_g2(vkey["vk_gamma_2"])
    vk_delta = _parse_g2(vkey["vk_delta_2"])
    ic       = [_parse_g1(p) for p in vkey["IC"]]

    # Accumulate public inputs: vk_x = IC[0] + sum(signal[i] * IC[i+1])
    vk_x = ic[0]
    for i, sig in enumerate(public_signals):
        scalar = int(sig) % curve_order
        vk_x = add(vk_x, multiply(ic[i + 1], scalar))

    # Groth16 check: e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
    #
    # Derived from:  e(A, B) = e(alpha, beta) * e(vk_x, gamma) * e(C, delta)
    # Since e(-A, B) = e(A, B)^-1, multiply both sides:
    #   e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) = 1
    result = (
        pairing(pi_b,    neg(pi_a)) *
        pairing(vk_beta, vk_alpha)  *
        pairing(vk_gamma, vk_x)     *
        pairing(vk_delta, pi_c)
    )
    return result == FQ12.one()


# ─── Public API ───────────────────────────────────────────────────────────────


def verify_dedup_proof(dedup_hash: str, proof: dict) -> bool:
    """
    Verify a Groth16 dedup proof generated by the VP SDK.

    dedup_hash: Poseidon output (decimal string) — as stored in dedup_registry
    proof:      Groth16 proof object { pi_a, pi_b, pi_c, protocol, curve }

    Returns True if proof is valid, False otherwise.
    Raises FileNotFoundError if vkey.json is missing.
    """
    # Allow tests to skip verification
    if os.environ.get("ZK_SKIP_VERIFY") == "true":
        return True

    vkey = _load_vkey()
    return _groth16_verify(vkey, [dedup_hash], proof)
